version: 2.1

parameters:
  node-version:
    type: string
    default : "16.19.1"

orbs:
  node: circleci/node@4.7.0

workflows:
  master:
    jobs:
      - node/test:
          name: test
          pkg-manager: yarn
          version: <<pipeline.parameters.node-version>>
          requires:
            - lint
      - node/run:
          name: build
          pkg-manager: yarn 
          yarn-run: build
          version: <<pipeline.parameters.node-version>>
          requires:
            - test
      - node/run:
          name: lint
          pkg-manager: yarn 
          yarn-run: affected:lint
          version: <<pipeline.parameters.node-version>>